### ISSUE TITLE
MAX_ARRAY_INDEX = 2 ** 53 - 1; Unexpected token *

### ISSUE THREAD

**Issue by h2nguyen** [jonkemp/package-utils#1]
Hi Jonathan,

we use one of your node page and we seem to have an issue with your latest release change (from yesterday):

```
10:29:58       [exec] <my-path>/node_modules/@jonkemp/package-utils/index.js:6
10:29:58       [exec] const MAX_ARRAY_INDEX = 2 ** 53 - 1;
10:29:58       [exec]                            ^
10:29:58       [exec] 
10:29:58       [exec] SyntaxError: Unexpected token *
10:29:58       [exec]     at createScript (vm.js:56:10)
10:29:58       [exec]     at Object.runInThisContext (vm.js:97:10)
10:29:58       [exec]     at Module._compile (module.js:549:28)
10:29:58       [exec]     at Object.Module._extensions..js (module.js:586:10)
10:29:58       [exec]     at Module.load (module.js:494:32)
10:29:58       [exec]     at tryModuleLoad (module.js:453:12)
10:29:58       [exec]     at Function.Module._load (module.js:445:3)
10:29:58       [exec]     at Module.require (module.js:504:17)
10:29:58       [exec]     at require (internal/module.js:20:19)
10:29:58       [exec]     at Object.<anonymous> (<my-path>/node_modules/flat-util/index.js:1:100)
10:29:58
```
Anything you can do from your side? Or hint for us to resolve this? Thanks!

Btw, we are currently using node with version v6.13.1

Cheers,

--hai

**Comment by jonkemp** [comment]
What package are you using? node 6.x is not supported.

**Comment by h2nguyen** [comment]
We are using package-utils, the day before your upgrade it was working tho. Thus, it means that `package-utils` is not compatible for 6.x version. Seems like we need to upgrade our node, however, any chance to make it backward compatible? E.g. provide the versioning (release-commits or release tags) for this package, so that we can still use the old one? Thanks!

**Comment by jonkemp** [comment]
I'm guessing that you are using something downstream that depends on this package. If I know what that is I can provide the version number. No plans for backwards compatibility at this time.

**Comment by h2nguyen** [comment]
ah, we are using inline-css, gulp-inline-css, flat-util

**Comment by himanshusinghs** [comment]
Same issue here. `inline-css` fails for node 6 as this package is one of the dependency of `inline-css` > `extract-css`
